### ISSUE TITLE
Problems with sending coverage statistic

### ISSUE THREAD

**Issue by mrkkrp** [sviridov/undercover.el#10]
First of all, I think you've done great work with this hack, but for some reason I cannot get it right for my project. Here is the repo:

https://github.com/mrkkrp/mmt

I've seen this: https://github.com/sviridov/undercover.el-usage-example , but unfortunately I don't see any principal differences between my project and the example.

In my case, Travis CI succeeds, but there is no

```
Wrote /tmp/undercover_coveralls_report
Sending: report to coveralls.io
Sending: OK
```

in the log, and here it is: https://travis-ci.org/mrkkrp/mmt/jobs/71423286#L328.

The stuff drives me crazy. Any idea why this might happen?

P.S. Я выбрал английский для общения для пользы будующих пользователей, хотя я видел описания подобных проблем в Closed Issues, так что прецидент уже есть, но чем больше примеров разрешенных проблем тем лучше. Спасибо!

**Comment by sviridov** [comment]
@mrkkrp `undercover.el` doesn't support test coverage for byte-compiled files. So, if you want to run tests with compiled files and have test coverage report you need to change your test cycle to:

```bash
cask exec ert-runner
cask build
cask exec ert-runner
```

Or you can just ignore `cask build` if byte compiling is not important for your project.

> I think you've done great work with this hack

Thanks a lot!

**Comment by sviridov** [comment]
@mrkkrp, I will fork your repository to support you)

**Comment by mrkkrp** [comment]
Doesn't seem to work: https://travis-ci.org/mrkkrp/mmt/jobs/71432656

FYI

```
cask exec ert-runner
cask build
cask exec ert-runner
```
doesn't work either.

**Comment by mrkkrp** [comment]
`-L .` results in:
```
Ran 0 tests in 0.000 seconds
```
at least for me, not sure why. I haven't tested Emacs Lisp code before.

**Comment by sviridov** [comment]
@mrkkrp Yeah, I already fix this problem, but I have problem with `mmt-once-only` macros expansion (which ruins build). I will try to fix it. You can try this:

```elisp
ELISP> (macroexpand-1 '(mmt-once-only (a b) `(+ ,a ,b)))
```

You will see this strange line:

```elisp
  `(let
       ((\,  ;; <-----
         `(,ONCE-ONLY20 ,a)
```

**Comment by mrkkrp** [comment]
@sviridov, Well, everything is possible, it's not tested yet :-) I have Common Lisp background, Emacs Lisp may behave a bit differently in case of nested backquotes... this is weird, I will try fix find out what's wrong.

**Comment by mrkkrp** [comment]
There may be a bug in Emacs: http://stackoverflow.com/questions/17394638/nesting-backquote-and-in-emacs-lisp
...or is it a feature?

Maybe the problem can be solved by replacing of \` character with `(backquote ...)` form. Let's see.

**Comment by mrkkrp** [comment]
Oh, no, using `backquote` form is a bad idea. There should be a way to fix it... You can just commend entire `mmt-once-only` and it will be fine.

**Comment by mrkkrp** [comment]
http://www.emacswiki.org/emacs/macro-utils.el

Here, the man is very cautious to avoid nesting of backquotes. This thing is obviously not allowed. Gonna construct it hard way...

**Comment by sviridov** [comment]
So, explanation:

- `ert-runner` have naming conventions. All your test file names should ends with `-test.el` to be automatically load.
- when you have tried `-l mmt.el test/mmt-init.el`, you actually loaded `mmt` before `undercover` (`require` do nothing when file is already loaded), so `undercover` was not able to "wrap" your code.

**Comment by mrkkrp** [comment]
Perfect. I think the badge will be refreshed after all. Thank you!
