### ISSUE TITLE
not working in ensime anymore

### ISSUE THREAD

**Issue by fommil** [sviridov/undercover.el#11]
:cry: I think I broke it at some point and didn't realise which commit did it. Can you please have a look and see if we're doing anything that might cause a problem?

https://github.com/ensime/ensime-emacs/blob/master/test/dotemacs_test.el

https://github.com/ensime/ensime-emacs/blob/master/ensime-test.el#L2039

we're doing `(kill-emacs 1)` with a kill hook to dump the stack of the exit point for debugging, that's the thing that makes me think we might have done something.

To run: install a Java 6 and put `sbt` on your `PATH` https://github.com/paulp/sbt-extras/blob/master/sbt

```
export JDK_HOME=/usr/lib/jvm/jdk-6-oracle-x64
export UNDERCOVER=t
test/run_emacs_tests.sh
```

**Comment by sviridov** [comment]
@fommil Sure, I will take a look.

**Comment by sviridov** [comment]
@fommil Is `COVERALLS_REPO_TOKEN` setted for test enviroment?

**Comment by fommil** [comment]
Yeah, but I don't tend to set it when running locally. Will undercover silently fail to produce the report if it is not set?

**Comment by fommil** [comment]
Oh actually, I guess it's not set for PRs. I can add it for that reason.

**Comment by sviridov** [comment]
@fommil `undercover.el` will do nothing until `TRAVIS=TRUE` or `COVERALLS_REPO_TOKEN` is setted.

**Comment by sviridov** [comment]
Quote  from README.md:

If you don't use `Travis CI` you need to set `COVERALLS_REPO_TOKEN` environment variable before running tests, for example:

```bash
$ COVERALLS_REPO_TOKEN=<your-coveralls-repo-token> cask exec ert-runner
```

**Comment by fommil** [comment]
ok, cool, that's likely it then! thanks :blush:
