### ISSUE TITLE
Show warning when no files found

### ISSUE THREAD

**Issue by sviridov** [sviridov/undercover.el#15]
This issue is based on @cpitclaudel feedback [here](https://github.com/sviridov/undercover.el/issues/14):

> @sviridov Thanks for the examples, but they didn't work for me at first; I did figure it out after a long while of debugging, but maybe it would be useful to highlight in one of the examples that the libraries shouldn't be compiled?

> Even better, it would be nice if undercover could complain if no files at all have been tested after a full run. Something like this maybe?

> ```
Undercover: No tests seem to have run. Make sure that your files are not compiled?
```

@cpitclaudel, there is warning about byte-compiled files in `README.md`:

> - it doesn't support test coverage for byte-compiled files;

But I agree that such runtime warning will be useful. Will implement it during this week.

**Comment by cpitclaudel** [comment]
> @cpitclaudel, there is warning about byte-compiled files in README.md:

Indeed, and the crazy part is that I read that warning and thought "ok, noted"; but then it took me an hour to connect the dots when things where failing...

**Comment by sviridov** [comment]
Done. Will be released with next melpa build.
