### ISSUE TITLE
Error while covering /home/travis/build/haskell/haskell-mode/inf-haskell.el

### ISSUE THREAD

**Issue by gracjan** [sviridov/undercover.el#16]
```
UNDERCOVER: error while covering /home/travis/build/haskell/haskell-mode/inf-haskell.el
UNDERCOVER: please open a new issue at https://github.com/sviridov/undercover.el/issues
```

Error visible in https://travis-ci.org/haskell/haskell-mode/jobs/117687025

The file in question [`inf-haskell.el`](https://github.com/haskell/haskell-mode/blob/master/inf-haskell.el).

I do not know how to get more information.

**Comment by sviridov** [comment]
@gracjan thanks! I will take a look.

**Comment by sviridov** [comment]
@gracjan this error happens because `edebug` is unable to parse `inferior-haskell-send-decl-post-filter`.

Something wrong with this syntax:

```emacs-lisp
#1=(string-match inferior-haskell-multiline-prompt-re string)
...
(while #1#
```

Is it some kind of reader macro? Where it's defined? Maybe we can change definition of `inferior-haskell-send-decl-post-filter` to not use it?

**Comment by gracjan** [comment]
Thanks for investigating, I think we can handle this on our end.

**Comment by gracjan** [comment]
It's this: http://www.gnu.org/software/emacs/manual/html_node/elisp/Circular-Objects.html

**Comment by sviridov** [comment]
Ok, thanks for the link, I will add note about it in README
