### ISSUE TITLE
"error while covering" with destructuring binds and Emacs 24.3+

### ISSUE THREAD

**Issue by liblit** [sviridov/undercover.el#19]
My [`demangle-mode`](https://github.com/liblit/demangle-mode) Emacs lisp project initially worked well with `undercover.el`, but recent changes to my code have caused an `error while covering` message to appear. Indeed, the coverage information is incomplete or missing when I see that message. In particular, [the Travis-CI run of my version 09036fd](https://travis-ci.org/liblit/demangle-mode/builds/151328742) worked fine on all seven Emacs versions tested. However, [the Travis-CI run of the next revision (8df9e04)](https://travis-ci.org/liblit/demangle-mode/builds/151338664), exhibits the problem under Emacs 24.3 and later, while still working correctly under Emacs 24.1 and 24.2.

For your convenience, here’s [a comparison between the good and bad versions](https://github.com/liblit/demangle-mode/commit/8df9e04d3d8542d034c31306b6356b93a1724aa1). As you can see, the main change was to use Common Lisp `cl-defun` and `cl-destructuring-bind` instead of `pcase`. Perhaps that’s a helpful clue?

Many thanks for any help you can provide!

**Comment by sviridov** [comment]
Thanks for the report will investigate

**Comment by sviridov** [comment]
@liblit, it looks like `cl-defun` should not support parameters destruction, I assume it based on:

- Quote from [this page](https://www.gnu.org/software/emacs/manual/html_node/cl/Argument-Lists.html):

  > cl-defun
This form is identical to the regular defun form, except that arglist is allowed to be a full Common Lisp argument list.

  But CL `defun` doesn't support destructing.

- Definition of edebug spec for `cl-defun` does not support destruction too. By the way that is way you can see this error.

I will suggest to use `destructuring-bind` explicitly, something like this:

```emacs-lisp
(cl-defun demangler-answer-received (some-argument answer)
  "Process a response received from the demangler transaction queue.

START and END are markers indicating where the MANGLED-ORIGINAL
symbol text appeared.  ANSWER is the raw response received from
the `demangler-queue'."
  (destructuring-bind (mangled-original start end) some-argument
    (let ((demangled (substring answer 0 -1))
          (buffer (marker-buffer start)))
      (with-current-buffer buffer
        (let ((mangled-current (buffer-substring-no-properties start end)))
          (when (and (string= mangled-original mangled-current)
                     (not (string= mangled-current demangled)))
            (with-silent-modifications
              (font-lock-prepend-text-property start end 'face demangle-show-as)
              (cl-ecase demangle-show-as
                ('demangled
                 (put-text-property start end 'display demangled)
                 (put-text-property start end 'help-echo mangled-current))
                ('mangled
                 (put-text-property start end 'help-echo demangled))))))))))
```

Please let me know if it works for you.

**Comment by liblit** [comment]
Thank you for looking into this, @sviridov! `cl-defun` definitely *does* do destructuring, though. Closer to the bottom of [the page you linked to](https://www.gnu.org/software/emacs/manual/html_node/cl/Argument-Lists.html):

> Argument lists support *destructuring*. In Common Lisp, destructuring is only allowed with `defmacro`; this package allows it with `cl-defun` and other argument lists as well.

The help documentation for `cl-defun` agrees:

> VAR maybe be replaced recursively with an argument list for destructing

Empirically, I can confirm that this works:

```elisp
(cl-defun test ((a (b c) d))
  (format "%s; %s; %s; %s" a b c d))

(test '(1 (2 3) 4))
	⇒ "1; 2; 3; 4"
```

So if the `edebug` spec for `cl-defun` does not support destructuring, then the `edebug` spec is buggy. I am happy to report this as an Emacs bug against the `cl` package, but it would be nice to suggest a fix too. Presumably the `(def-edebug-spec cl-lambda-list ...)` definition in `cl-macs.el` needs to change. But how? But I definitely do not understand `edebug` specs well enough to know what belongs here. Do you?

**Comment by sviridov** [comment]
Ok, thanks for clarification @liblit!

Yeah, it's `cl-lambda-list`, but unfortunately I cannot provide new definition for it right now.

**Comment by liblit** [comment]
Understandable. This is some scary stuff.

In lieu of a suggested fix, do you know of a good way to demonstrate that there is a problem in the `edebug` spec that does not require using `undercover.el`? Perhaps something I can recreate with a suitable elisp fragment and just the regular debugging activities like calling `(debug)`? If I am going to report this as a bug, I would like to at least demonstrate that there is indeed a problem, and do so with as little third-party code as possible.

**Comment by sviridov** [comment]
@liblit, sure:

- Go to `emacs-lisp-mode` buffer

- Insert something like this:

  ```emacs-lisp
  (require 'cl)

  (cl-defun sum ((x y)) (+ x y))
  ```

- Run `M-x eval-buffer` (everything should be fine)

- Now run `M-x edebug-all-defs` (is should autoload `edebug`)

- Repeat `M-x eval-buffer` (now you should see a error)

**Comment by liblit** [comment]
Reported as [Emacs bug #24255](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24255). Thank you for tracking this down and distilling it to something suitable for a good bug report.

**Comment by xendk** [comment]
Looks like this will be fixed in Emacs 26?

**Comment by sviridov** [comment]
Good news, thanks for managing it!
