### ISSUE TITLE
Fail for ejc-sql

### ISSUE THREAD

**Issue by kostafey** [sviridov/undercover.el#23]
```
UNDERCOVER: error while covering /home/travis/build/kostafey/ejc-sql/ejc-sql.el
UNDERCOVER: please open a new issue at https://github.com/sviridov/undercover.el/issues
```

Here is a source:
https://github.com/kostafey/ejc-sql/blob/new-cache/ejc-sql.el

Can I provide some more info for debug?

**Comment by sviridov** [comment]
Hi @kostafey, thanks for the report. I will investigate it a bit later.

Yes, you can provide additional information by doing following:

- Go to `ejc-sql.el` file in Emacs
- Run `M-x edebug-all-defs`
- Run `M-x eval-buffer`
- At this point you should be able to see exact place where error happens

**Comment by kostafey** [comment]
Ok, it's my mistake. Here `&optional` is redundant:

```lisp
(cl-defun my-fn (var &optional &key other-vars...
```

This is sufficient:
```lisp
(cl-defun my-fn (var &key other-vars...
```
Thank you.
