### ISSUE TITLE
Merge two coverage reports before sending

### ISSUE THREAD

**Issue by DamienCassou** [sviridov/undercover.el#30]
I'm using both ert/ert-runner and buttercup for writing tests. Each one, by default, start Emacs, launch the tests, and quit Emacs. I guess that means 2 reports sent to coveralls.io.

**Comment by sviridov** [comment]
@DamienCassou, please take a look at https://github.com/sviridov/undercover.el-combined-usage-example.

Use `:send-report` option (it mentioned in README.md) to prevent first report send & merge reports.

**Comment by DamienCassou** [comment]
Thank you
