### ISSUE TITLE
Holes in coverage report when using macros

### ISSUE THREAD

**Issue by DamienCassou** [sviridov/undercover.el#31]
In [one](https://github.com/DamienCassou/beginend) of my projects, most code depends on macros to create functions. The coverage information is very weak: e.g., [lines 128 to 240](https://coveralls.io/builds/11621309/source?filename=beginend.el) are not subject to code coverage (in https://github.com/DamienCassou/beginend/pull/23).

**Comment by sviridov** [comment]
@DamienCassou, unfortunately, it looks like I can do nothing with it. `undercover.el` relies on `edebug` code parsing abilities. And it looks like `edebug` is not able to track dynamically generated functions.

**Comment by DamienCassou** [comment]
Thanks for your answer. I guess you can close the ticket now.
