### ISSUE TITLE
Ignore compiler warning ‘:send-report’ called as a function

### ISSUE THREAD

**Issue by DamienCassou** [sviridov/undercover.el#32]
$ echo "(when (require 'undercover nil t) (undercover \"xx.el\" (:send-report nil)))" > foo.el

    $ emacs --batch -Q -f batch-byte-compile foo.el
    In toplevel form:
    foo.el:2:4:Warning: ‘:send-report’ called as a function

`undercover` being a macro, `:send-report` does not have to be a function.

**Comment by DamienCassou** [comment]
I asked this question on stackoverflow too https://emacs.stackexchange.com/posts/33286

**Comment by sviridov** [comment]
Hi! Unfortunately I'm on vacation right now. I will be able to look into this issue after next week. Thanks for the report!

**Comment by sviridov** [comment]
Just to share some information. I made a test project to test this warning in proper conditions:

Cask file:

```elisp
(source melpa)
(source gnu)

(package-file "test.el")

(development
 (depends-on "undercover"))
```

test.el:

```elisp
;;; test.el --- Description

;; Version: 0.0.0

(when (require 'undercover nil t)
  (undercover "xx.el" (:send-report nil)))

(provide 'test.el)

;;; test.el ends here
```

I got slightly different issues:

```
In toplevel form:
test.el:8:4:Warning: ‘:send-report’ called as a function

In end of data:
test.el:13:1:Warning: the following functions are not known to be defined:
    undercover, :send-report
```

But when I replace test.el content:

```elisp
;;; test.el --- Description

;; Version: 0.0.0

(require 'undercover nil t)
(undercover "xx.el" (:send-report nil))

(provide 'test.el)

;;; test.el ends here
```

I see no warnings...

It looks like it something related to conditional statements. I'm not aware about any way  to fix this issue. And I found [this](https://emacs.stackexchange.com/questions/10688/compiling-warning-when-installing-auto-complete-package-in-emacs-24) intresting comment on stack exchange.

So until you know a way of fixing it, I think we should ignore this issue...

**Comment by DamienCassou** [comment]
Good enough. Thanks
