### ISSUE TITLE
Use undercover inside docker.

### ISSUE THREAD

**Issue by AfsmNGhr** [sviridov/undercover.el#33]
I'm using emacs inside the [docker container](https://github.com/AfsmNGhr/dockemacs).

#### Travis CI (public)

```yml
    environment:
      - TRAVIS=$TRAVIS
      - TRAVIS_JOB_ID=$TRAVIS_JOB_ID
```

- [Enviroment variables](https://travis-ci.org/AfsmNGhr/dockemacs/builds/271794540#L949)

```sh
emacs_1  | TRAVIS=true
emacs_1  | TRAVIS_JOB_ID=271794541
```

- [OK](https://travis-ci.org/AfsmNGhr/dockemacs/builds/271794540#L4664), build not found.

```sh
emacs_1  | Sending: report to coveralls.io
emacs_1  | Sending: OK
```

#### Travis CI (with encrypt token)

```yml
    environment:
      - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
```

- [Enviroment variables](https://travis-ci.org/AfsmNGhr/dockemacs/builds/271794540#L948)

```sh
emacs_1  | COVERALLS_REPO_TOKEN=[secure]
```

- [OK](https://travis-ci.org/AfsmNGhr/dockemacs/builds/271804717#L4655), build not found.

```sh
emacs_1  | Sending: report to coveralls.io
emacs_1  | Sending: OK
```

#### Travis CI (with raw token)

- Ok, build present, but not security.

```sh
emacs_1  | Sending: report to coveralls.io
emacs_1  | Sending: OK
```

How fix it?

**Comment by sviridov** [comment]
Hi @AfsmNGhr,

I'm sorry but I'm afraid I don't understand the issue.

> OK, build not found.
> Ok, build present, but not security.

What is `OK`? Which `build` found (or not found)? Are you talking about Coveralls build page?
Could you please provide a bit more detailed explanation of the issue?

**Comment by AfsmNGhr** [comment]
Yes, i'm talk about Coveralls build page. Did not found current build after send.
Found build on page only undercover with raw token (`COVERALLS_REPO_TOKEN`).
There's been no mistakes. So, what do you think happened here?

**Comment by sviridov** [comment]
So, 

> Travis CI (with encrypt token)

If this way doesn't work it means that Emacs is unable to get `COVERALLS_REPO_TOKEN` as an environment variable (or value of it is incorrect). Nothing can be done on `undercover.el` side here.

> Travis CI (public)

That is actually really strange. I'm not sure, maybe Coveralls was not able to extract information based on TRAVIS_JOB_ID or maybe it was a temporary issue with Coveralls... Are you able to reproduce it?

I will look into it more on weekends.

**Comment by sviridov** [comment]
It looks like [link](https://travis-ci.org/AfsmNGhr/dockemacs/builds/271794540#L948) to environment variables for the second case (Travis CI with encrypt token) is incorrect. I cannot find this line in the log:

> emacs_1  | COVERALLS_REPO_TOKEN=[secure]

I'm sorry, but I don't have time to actively debug this issue. If you really want to fix it, I would recommend you to fork `undercover.el` remove `shut-up` call around [curl](https://github.com/sviridov/undercover.el/blob/master/undercover.el#L392) request to see coveralls response. Maybe it would clarify the issue.

Sorry for not being really useful.

**Comment by AfsmNGhr** [comment]
Hi, @sviridov,

I decided to test `undercover.el` [again](https://travis-ci.org/AfsmNGhr/dockemacs/jobs/587158598#L2804).
Caught a new warning and [fix it](https://github.com/AfsmNGhr/dockemacs/commit/6950137809c7064090cea25833bc38a094200dc9). 
Now I use `byte-compile-file` after tangling org file.

Tested both options through [travis public api](https://github.com/AfsmNGhr/dockemacs/blob/24f4845ade9ac3c45d4059a9ec627d6d1ed49dbc/.travis.yml#L23) and [with token](https://github.com/AfsmNGhr/dockemacs/blob/6950137809c7064090cea25833bc38a094200dc9/.travis.yml#L23). 
Both works but when I used token for send report to it was [associated](https://coveralls.io/repos/176752/builds) `HEAD` instead master.

I don't know what changes made it work, as everything has changed a lot during this time. 

- Alpine 3.6 -> 3.10 (more probable)
- Deleted docker-compose
- Multi-stage build

**Comment by sviridov** [comment]
Hi @AfsmNGhr, great to hear that it works!
