### ISSUE TITLE
Cannot run coverage

### ISSUE THREAD

**Issue by lazywithclass** [sviridov/undercover.el#4]
First of all thanks for this project.

I'm trying to add coverage to [Spacemacs](https://github.com/syl20bnr/spacemacs) but I fail to understand how to correctly configure the project.
I have near no experience in Emacs Lisp testing, but I really feel the above project could use a code coverage tool to help understanding where to put effort.

I wrote [a sample project](https://github.com/lazywithclass/sample-undercover.el-project) to try to understand what I'm doing wrong but with no results.
I am running the tests with `cask exec ert-runner`.

Any hint of help will be highly appreciated!

**Comment by sviridov** [comment]
Hi! I hope this steps will help you:

1. First of all you need to write some tests for you project. There is a lot of useful information about Emacs Lisp testing at Johan Andersson's [blog](http://rejeep.github.io/).
2. Then you need to configure [Travis CI](https://travis-ci.org) for your project to run this tests automatically ([example](https://github.com/sviridov/undercover.el/blob/master/.travis.yml) for Cask and ert-runner).
3. Then you need to enable your project at [Coveralls](https://coveralls.io/).
4. Then you need to add `undercover.el` to your project dependencies. If you are using Cask it's very simple. You can see an example at README.md.
5. Then you need to instrument your code with undercover.el before running tests. See some examples below.
6. That's all. Your project test coverage will be collected and sent to [Coveralls](https://coveralls.io/) with next [Travis CI](https://travis-ci.org) job.

I suggest you to look at undercover.el usage in real projects. Here some examples:

- [expand-region.el](https://github.com/magnars/expand-region.el/commit/0b1c32f1f05e7c80b547f042f287dd68c8db96f2)
- [s.el](https://github.com/magnars/s.el/commit/1cb3c07ec934087a0ec05b4e817face12ce6713b)
- [edbi-database-url](https://github.com/proofit404/edbi-database-url/commit/1c11800f2527d8240edba717e90f6d440f005540)

I can try to find some time to fix your sample project at weekend.

**Comment by lazywithclass** [comment]
Hey, thank you so much.

I've followed the guide at point 1. but I will take this chance to give the whole process another go, it seems pretty straightforward, I don't know why I'm struggling this much :D

**Comment by sviridov** [comment]
@lazywithclass I had made a [undercover.el-usage-example](https://github.com/sviridov/undercover.el-usage-example). I hope it will help you.

**Comment by lazywithclass** [comment]
Thank you so much for this!

After cloning it I've run `cask install`, so I got all dependencies. 
I've then run 

```bash
$ cask exec ert-runner
.

Ran 1 test in 0.001 seconds
```

...and I think I got the expected output, but what about the coveragem how do I get that?
I saw that in undercover.el you are generating a json report, so I was and currently am looking in https://github.com/sviridov/undercover.el/blob/master/test/test-helper.el#L22 to see if I've missed some configuration.
Do you have any hints about that?

Thank you again.

**Comment by sviridov** [comment]
> I saw that in undercover.el you are generating a json report, so I was and currently am looking in https://github.com/sviridov/undercover.el/blob/master/test/test-helper.el#L22 to see if I've missed some configuration.

@lazywithclass This code is an inner `undercover.el` hacks to create `undercover.el` coverage with `undercover.el` itself. It's not a public API.

`undercover.el` assumes that test coverage will be done under Travis CI job and not on your local machine. So you need to push something to Github (with enabled Travis CI and Coveralls).

Look at [this](https://travis-ci.org/sviridov/undercover.el-usage-example/jobs/49926953#L508) line of build log. It's a moment when all happens.

**Comment by lazywithclass** [comment]
Thak you so much for your help, it took me a while but now I get it!
