### ISSUE TITLE
Unable to install via cask with emacs 26.1

### ISSUE THREAD

**Issue by bhrgunatha** [sviridov/undercover.el#41]
I'm using Arch Linux 64 bit with their [emacs package](https://www.archlinux.org/packages/extra/x86_64/emacs/). 
emacs: 26.1
cask : 0.8.4

I'm trying to [install pdf-tools](https://github.com/politza/pdf-tools) via cask which is unsuccessful.   

Next I tried to build and install pdf-tools from source which also fails indicating that [cask can't install undercover](https://github.com/politza/pdf-tools/issues/396) from melpa. 

```
Using Emacs 26.1 
cask install
Dependency undercover failed to install: Variable binding depth exceeds max-specpdl-size
Output:
Setting `package-selected-packages' temporarily since "emacs -q" would overwrite customizations
Contacting host: melpa.org:443
Checking /home/bhrgunatha/scratch/pdf-tools/.cask/26.1/elpa/shut-up-20150423.522...
Compiling /home/bhrgunatha/scratch/pdf-tools/.cask/26.1/elpa/shut-up-20150423.522/shut-up-autoloads.el...
Compiling /home/bhrgunatha/scratch/pdf-tools/.cask/26.1/elpa/shut-up-20150423.522/shut-up-pkg.el...
Compiling /home/bhrgunatha/scratch/pdf-tools/.cask/26.1/elpa/shut-up-20150423.522/shut-up.el...
~/.cask/cask-cli.el:Error: Variable binding depth exceeds max-specpdl-size
Done (Total of 0 files compiled, 2 skipped)
Error loading autoloads: (error Variable binding depth exceeds max-specpdl-size)
Error in package--load-files-for-activation: (error Variable binding depth exceeds max-specpdl-size)

make: *** [Makefile:44: .cask/26.1] Error 255
```

The Cask file for pdf-tools is:
```
(source gnu)
(source melpa)

(package-file "lisp/pdf-tools.el")

(files "lisp/*.el"
       "README"
       "server/epdfinfo")

(development
 (depends-on "let-alist")
 (depends-on "tablist")
 (depends-on "ert-runner")
 (depends-on "undercover"))
```

let-alist, tablist and ert-runner are installed OK but undercover fails.

**Comment by sviridov** [comment]
Hi @bhrgunatha, sorry for the late response, but I'm afraid I cannot help with this one.
The error message means nothing to me. Could you please create an issue in cask repository and link it here?

**Comment by macie** [comment]
I successfully installed `pdf-tools` on `Arch Linux 64 bit` with `emacs 26.1` and `cask 0.8.4`. It looks like resolving [metioned cask issue](https://github.com/politza/pdf-tools/issues/396) helped.

I think that this issue can be closed.

**Comment by sviridov** [comment]
@macie, great, thank you!
