### ISSUE TITLE
Error while covering ...

### ISSUE THREAD

**Issue by galaunay** [sviridov/undercover.el#43]
Hi,
I have a well this error poping up in travis:
```
UNDERCOVER: error while covering /home/travis/build/galaunay/poetry.el/poetry.el
UNDERCOVER: please open a new issue at https://github.com/sviridov/undercover.el/issues
```

(only for emacs <= 25)

I tried what you recommend [here](https://github.com/sviridov/undercover.el/issues/40#issuecomment-399855951). edebug complains at the third line of this function:
```Elisp
(defmacro poetry-with-current-file (file &rest body)
  "Execute the forms in BODY while temporary visiting FILE."
  `(save-current-buffer     # HERE
     (let* ((file ,file)
            (keep (find-buffer-visiting file))
            (buffer (find-file-noselect file)))
       (set-buffer buffer)
       (prog1
           (progn
             ,@body)
         (unless keep
           (kill-buffer buffer))))))
```

I understand from undercover readme that `it based on edebug and can have some issues with macros coverage.`, but is there anything I can do about it ?

**Comment by sviridov** [comment]
Hi @galaunay! I'm not actively supporting this project, but please, read this comment: https://github.com/sviridov/undercover.el/issues/40#issuecomment-399855951. It should help you to localize the issue.
