### ISSUE TITLE
overriding exit codes?

### ISSUE THREAD

**Issue by fommil** [sviridov/undercover.el#5]
We're exting with 0 from our test suite, but somehow the emacs process is exiting with 1.

https://travis-ci.org/ensime/ensime-emacs/builds/52718969

It looks like comms with coveralls.io is happening after we exit 0.

1. Is undercover/coveralls perhaps changing the exit code?
2. Is there a way to delay upload so that it can be done in a separate process?

**Comment by sviridov** [comment]
> Is undercover/coveralls perhaps changing the exit code?

No it's shouldn't.

> Is there a way to delay upload so that it can be done in a separate process?

Yes. You can use `:report-file` option:

```lisp
(undercover "*.el" (:report-file "/tmp/local-report.json"))
```

and then send it with something like that:

```bash
curl -v -include --form json_file=@/tmp/local-report.json https://coveralls.io/api/v1/jobs
```

**Comment by fommil** [comment]
ok cool, thanks, I'll try that and see if it solves the problem.

**Comment by fommil** [comment]
well, I'm still getting my exit 1 after disabling undercover, so it's definitely not a valid ticket.
