### ISSUE TITLE
RFE: merge reports

### ISSUE THREAD

**Issue by fommil** [sviridov/undercover.el#6]
We have several batch jobs that we run when we're running our tests, you can loosely think of them as:

* setup/provisioning
* unit tests
* integration tests

But when we do a coveralls run, it only works for one batch process. It would be really good to be able to merge the reports together.

**Comment by sviridov** [comment]
@fommil Ok, I will do it. But I'm really busy right now, so it will take some time. Maybe week.

**Comment by fommil** [comment]
no rush! We're actually struggling to get any coverage reports at the moment. I think I changed something stupid and need to work out how I broke it first.

**Comment by sviridov** [comment]
@fommil Finally I found some time to implement this RFE. You can get it from `merge-reports` branch. There is backward incompatible API change, so I will make some preparation before merge it into master. But before doing it I want to be sure that it works for you.

Old version of API:

- Set `report-file` option if you want to save coverage report locally.

New version of API:

- Set `report-file` option if you want to change report location. `undercover.el` will try to merge new report with existing one.
- Set `send-report` option to `nil` if you want to save coverage report locally.

So, You can write something like this:

```lisp
(undercover "ensime*.el"
   (:report-file "coveralls.json")
   (:send-report nil) ; for manual report send
   (:send-report (getenv "LAST_JOB_INDICATOR")) ; for automatic send from last batch job
   (:exclude "ensime-test.el" "dotemacs_test.el" "ensime-inspector.el"))
```

I will wait your feedback.

**Comment by sviridov** [comment]
@fommil ping

**Comment by fommil** [comment]
oh sorry. I've got an eye infection that will take a few weeks to clear up, so I'm under doctor's orders not to use my computer in the evenings. Can you ping me again in two weeks please? (or make the backwards compatibility changes as a PR to ensime-emacs and we'll merge ASAP). I guess we need to set `:send-report` to `nil` and remove our `report-file` setting? Then we'll look at breaking our testing into separate parts, which is a really amazing thing to be able to do.

**Comment by sviridov** [comment]
>  I guess we need to set :send-report to nil and remove our report-file setting?

Yes, we need to set :send-report to nil, but we can leave :report-file without change.

> Can you ping me again in two weeks please?

@fommil Sure. Get well soon!

**Comment by sviridov** [comment]
> Can you ping me again in two weeks please?

@fommil ping

**Comment by fommil** [comment]
sorry for taking so long. I've raised a PR... can you please review it? We'll go simple to start with and then look at actually merging the phases later (it would require a refactor of our build) https://github.com/ensime/ensime-emacs/pull/134

**Comment by sviridov** [comment]
> I've raised a PR... can you please review it?

@fommil Sure, but I will do it tomorrow. I just don't have enough time today.
