### ISSUE TITLE
support more than just travis

### ISSUE THREAD

**Issue by fommil** [sviridov/undercover.el#7]
Would it be hard to support other CI environments, such as shippable?

http://docs.shippable.com/en/latest/config.html#common-environment-variables

**Comment by sviridov** [comment]
No, I think it will be easy enough.

**Comment by sviridov** [comment]
Should I consider it as RFE?

**Comment by fommil** [comment]
yes please :smile: we're moving to Shippable which uses docker images

**Comment by sviridov** [comment]
Now you can use not only TravisCI (commit will be soon on melpa). Appropriate section was added to README:

- If you don't use [Travis CI](https://travis-ci.org/) you need to set `COVERALLS_REPO_TOKEN` environment variable before running tests, for example:

  ```sh
  $ COVERALLS_REPO_TOKEN=<your-coveralls-repo-token> cask exec ert-runner
  ```

**Comment by fommil** [comment]
awesome! :smile: thank you so much

**Comment by fommil** [comment]
I'm running on shippable and doing a manual upload afterwards, and I'm getting this

```
{"message":"Couldn't find a repository matching this job.","error":true}
```

is there some other envvar that you need to populate the repo name?

https://app.shippable.com/builds/550d705921d6a90b00366d57 => 4 => `after_success`

**Comment by fommil** [comment]
I'm regenerating our token, and trying again. Might be a coveralls issue.

**Comment by fommil** [comment]
regenerating the token didn't help.

**Comment by fommil** [comment]
ah! It's because I'm doing a manual upload. I'm doing this

```
curl -v -include --form json_file=@coveralls.json https://coveralls.io/api/v1/jobs ;
```

do I need to add a header or something?

**Comment by sviridov** [comment]
> https://app.shippable.com/builds/550d705921d6a90b00366d57

The build you're looking for wasn't found. :(

> ah! It's because I'm doing a manual upload

Nope. I've tested it and it works fine. Please, check that `coveralls.json` contains `repo_token` field.

**Comment by fommil** [comment]
@sviridov no, it doesn't contain the token if I use the `:report-file` approach. It works fine if I just allow undercover to do the upload.

**Comment by fommil** [comment]
Btw, I've just realised that this approach will never work for pull requests on shippable as secure env vars are not made visible: http://docs.shippable.com/en/latest/config.html#secure-env-variables

Hmm, how does Travis do it? Does coveralls need to support shippable directly?

**Comment by fommil** [comment]
BTW, if I use the token, all our pull requests are still showing up as "push" instead of "pull request" on coveralls: https://coveralls.io/builds/2165790

Is there maybe something else that needs to be set?

**Comment by sviridov** [comment]
> @sviridov no, it doesn't contain the token if I use the :report-file approach. It works fine if I just allow undercover to do the upload (I tried this locally).

And `:report-file` approach was tested locally? It's really strange because `undercover.el` uses same `curl` command to send same report file. There is no extra logic for `:report-file`. I will do some experiments with fork.

> Btw, I've just realised that this approach will never work for pull requests on shippable as secure env vars are not made visible: http://docs.shippable.com/en/latest/config.html#secure-env-variables

> Hmm, how does Travis do it? Does coveralls need to support shippable directly?

Travis is very special for Coveralls. They getting all information via Travis API and you don't need repository token or some other secret information. Right now I don't see any other way except making your token open. But I'm not shippable expert and I might miss something.

> BTW, if I use the token, all our pull requests are still showing up as "push" instead of "pull request" on coveralls: https://coveralls.io/builds/2165790

> Is there maybe something else that needs to be set?

Yeah, it's need to be set by `undercover.el`. I will do it for shippable after we fix first issue.

**Comment by fommil** [comment]
awesome, thanks for looking into this

**Comment by sviridov** [comment]
@fommil I have some problems with building a fork of ensime.

> Error in YML for sviridov/ensime-emacs
> No image name provided in "build_image" tag. 

Maybe you have any idea how to fix that?

**Comment by fommil** [comment]
oh, that's probably because you're trying to build on your account instead of in a PR to ensime-emacs. We use dedicated hosts with custom docker images.... just raise a PR and you'll get to use our build.

**Comment by sviridov** [comment]
@fommil Sorry for the huge dellay, I was busy this days. Looks like build for my PR was ok, but I don't have read access for build log.

>  The build you're looking for wasn't found.

Maybe you have some idea how I can get build output?

**Comment by fommil** [comment]
uuugh, Shippable is really starting to annoy me. I'll temporarily add you as a collab on ensime.

@rorygraves @aemoncannon @edani FYI

**Comment by sviridov** [comment]
Hmm.. Shippable thinks that I'm not a part of ensime organization. I can't see ensime repositories or ensime organization. I already resynced my account and even recreated it. It didn't help.

**Comment by fommil** [comment]
yeah, another bug, enable private repos if you're ok with that. Apparently it's a bug in the github API (but I have my doubts)

**Comment by sviridov** [comment]
Ok, I can see it. But I notice that you have recent coveralls reports from shippable. It's ok now?

**Comment by fommil** [comment]
:smile: the problem is that it doesn't recognise when it's a Pull Request. We have the coveralls token so your recent changes allow us to do that. e.g. your PR didn't produce a coveralls report (which then reports back to github).

**Comment by sviridov** [comment]
@fommil done!)

Report: https://coveralls.io/r/ensime/ensime-emacs
Response on PR: ensime/ensime-emacs#123

**Comment by fommil** [comment]
yay! Thank you :smile: Can you please squash your changes here and I'll merge them in?

**Comment by sviridov** [comment]
@fommil done
