### ISSUE TITLE
Troubleshooting missing coverage

### ISSUE THREAD

**Issue by dmitrym0** [sviridov/undercover.el#73]
Hey folks,

Thanks for a wonderful package. I'm having a bit of a problem with undercover reporting zero coverage for one of my modules.

I'm confident that at least _some_ of the module is being executed since I see some `(message`s sprinkled in the console.

I dont see any errors, and some of my code is being reported as covered.

Emacs 29.1 on MacOS, Cask and Buttercup. 

Any advice on how to proceed with this?

**Comment by CyberShadow** [comment]
Hi @dmitrym0 ,

You may have already seen the "Troubleshooting" section: https://github.com/undercover-el/undercover.el#troubleshooting

Something to pay attention to is to make sure that the code in your module doesn't run before Undercover is initialized and has started collecting code coverage.

Generally, I suggest approaching this as with most other problems: try to reproduce the problem with a small example, then gradually introduce elements from your real project until you can pinpoint the source of the issue.

**Comment by dmitrym0** [comment]
Thanks for your advice @CyberShadow. I think this is a case of rubber ducky debugging :)

Anyway, it turns out that changing `load` to `require` fixed it. 

```diff
-(load "org-noter-org-roam")
+(require 'org-noter-org-roam)
```

Not sure what the difference is, but this is the fix.
